# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180805_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photo/%Y/%m/%d/'),
        ),
    ]
