# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_alamat_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_pemilik_kost',
            field=models.BooleanField(default=False),
        ),
    ]
